version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db_kitty:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    image: duzer61/kittygram_backend
    env_file: .env
    depends_on:
      - db_kitty
    volumes:
      - static:/backend_static
      - media:/media

  frontend:
    image: duzer61/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  
  gateway:
    image: duzer61/kittygram_gateway
    env_file: .env
    volumes:
      - static:/staticfiles/
      - media:/media
    ports:
      - 9000:80
